In [1]:
import pandas as pd
from datetime import time
from ipyfilechooser import FileChooser
from IPython.display import display
import os


# 🎛️ Interface de sélection de fichier
fc_input = FileChooser("//10.69.168.1/crnldata/forgetting/Carla", select_default=True,show_only_dirs=False, title="<b>Sélectionnez le fichier CSV</b>")
display(fc_input)

# 📂 Fonction appelée après sélection du fichier
def update_input_file(chooser):
    global input_file_path
    input_file_path = chooser.selected
    print(f"\n📂 Fichier sélectionné : {input_file_path}")

FileChooser(path='\\10.69.168.1\crnldata\forgetting\Carla', filename='', title='<b>Sélectionnez le fichier CSV…

In [2]:
# Utiliser directement la propriété .selected du sélecteur
if fc_input.selected:
    input_file_path = fc_input.selected
    print(f"📂 Fichier sélectionné : {input_file_path}")
    
    df = pd.read_csv(input_file_path)
    df.columns = df.columns.str.replace(r'\+AF8-', '_', regex=True)
    print(f"✅ Fichier chargé : {len(df)} lignes, {len(df.columns)} colonnes")
    display(df)
else:
    print("❌ Veuillez d'abord sélectionner un fichier dans l'interface ci-dessus")

📂 Fichier sélectionné : \\10.69.168.1\crnldata\forgetting\Carla\Fed\APPPS1\AHAD01.38\12 mois\AHAD01.38_05_01_2026au07_01_2026.CSV
✅ Fichier chargé : 996 lignes, 16 colonnes

,MM:DD:YYYY hh:mm:ss,Library_Version,Session_type,Device_Number,Battery_Voltage,Motor_Turns,FR,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time
0,1/5/2026 15:30:16,1.16.3,Light Trk,0,3.69,NaN,1,Left,Left,1,0,0,0,NaN,NaN,0.06
1,1/5/2026 15:30:23,1.16.3,Light Trk,0,3.69,4.0,1,Pellet,Left,1,0,1,0,0.06,NaN,NaN
2,1/5/2026 15:58:26,1.16.3,Light Trk,0,3.69,NaN,1,Right,Left,1,1,1,0,NaN,NaN,0.03
3,1/5/2026 15:58:41,1.16.3,Light Trk,0,3.69,NaN,1,Right,Left,1,2,1,0,NaN,NaN,0.07
4,1/5/2026 17:18:26,1.16.3,Light Trk,0,3.82,NaN,1,Left,Left,2,2,1,0,NaN,NaN,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,1/7/2026 5:37:16,1.16.3,Light Trk,0,4.13,NaN,1,Right,Right,409,262,321,0,NaN,NaN,0.00
992,1/7/2026 5:37:17,1.16.3,Light Trk,0,4.13,2.0,1,Pellet,Right,409,262,322,0,0.06,16.0,NaN
993,1/7/2026 5:37:47,1.16.3,Light Trk,0,4.13,NaN,1,Left,Left,410,262,322,0,NaN,NaN,0.00
994,1/7/2026 5:37:48,1.16.3,Light Trk,0,4.14,1.0,1,Pellet,Left,410,262,323,0,0.19,31.0,NaN
995,1/7/2026 5:37:49,1.16.3,Light Trk,0,4.14,NaN,1,LeftinTimeOut,Left,411,262,323,0,NaN,NaN,NaN

In [3]:
# 📌 Colonnes à supprimer
cols_to_drop = [
    'Library_Version', 'Session_type', 'Device_Number',
    'Battery_Voltage', 'Motor_Turns', 'FR'
]   
# 🧹 Supprimer les colonnes indésirables
df.drop(columns=[col for col in cols_to_drop if col in df.columns], inplace=True)
df

,MM:DD:YYYY hh:mm:ss,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time
0,1/5/2026 15:30:16,Left,Left,1,0,0,0,NaN,NaN,0.06
1,1/5/2026 15:30:23,Pellet,Left,1,0,1,0,0.06,NaN,NaN
2,1/5/2026 15:58:26,Right,Left,1,1,1,0,NaN,NaN,0.03
3,1/5/2026 15:58:41,Right,Left,1,2,1,0,NaN,NaN,0.07
4,1/5/2026 17:18:26,Left,Left,2,2,1,0,NaN,NaN,0.17
...,...,...,...,...,...,...,...,...,...,...
991,1/7/2026 5:37:16,Right,Right,409,262,321,0,NaN,NaN,0.00
992,1/7/2026 5:37:17,Pellet,Right,409,262,322,0,0.06,16.0,NaN
993,1/7/2026 5:37:47,Left,Left,410,262,322,0,NaN,NaN,0.00
994,1/7/2026 5:37:48,Pellet,Left,410,262,323,0,0.19,31.0,NaN
995,1/7/2026 5:37:49,LeftinTimeOut,Left,411,262,323,0,NaN,NaN,NaN

In [6]:
df = pd.read_csv(input_file_path, sep=',')

In [7]:

# 🕒 Convertir la colonne datetime
df['Datetime'] = pd.to_datetime(df['MM:DD:YYYY hh:mm:ss'], errors='coerce')
print(df['Datetime'].astype(str))  # Force l'affichage complet

# 🗓️ Extraire Date et Hour
df['Date'] = df['Datetime'].dt.date
df['Hour'] = df['Datetime'].dt.time

#df.rename(columns={'Active_Poke': 'ActivePoke'}, inplace=True)

# ☀️ Déterminer la période Day/Night
def get_period(hour):
    if pd.isnull(hour):
        return None
    if time(7, 0, 1) <= hour <= time(19, 0, 0):
        return "Day"
    else:
        return "Night"

df['Period'] = df['Hour'].apply(get_period)

# 💾 Enregistrer dans le même dossier avec _modifié
folder = os.path.dirname(input_file_path)
base = os.path.splitext(os.path.basename(input_file_path))[0]
output_file = os.path.join(folder, f"{base}_Periodic.csv")

df

0      2026-01-05 15:30:16
1      2026-01-05 15:30:23
2      2026-01-05 15:58:26
3      2026-01-05 15:58:41
4      2026-01-05 17:18:26
              ...
991    2026-01-07 05:37:16
992    2026-01-07 05:37:17
993    2026-01-07 05:37:47
994    2026-01-07 05:37:48
995    2026-01-07 05:37:49
Name: Datetime, Length: 996, dtype: object

,MM:DD:YYYY hh:mm:ss,Library_Version,Session_type,Device_Number,Battery_Voltage,Motor_Turns,FR,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time,Datetime,Date,Hour,Period
0,1/5/2026 15:30:16,1.16.3,Light Trk,0,3.69,NaN,1,Left,Left,1,0,0,0,NaN,NaN,0.06,2026-01-05 15:30:16,2026-01-05,15:30:16,Day
1,1/5/2026 15:30:23,1.16.3,Light Trk,0,3.69,4.0,1,Pellet,Left,1,0,1,0,0.06,NaN,NaN,2026-01-05 15:30:23,2026-01-05,15:30:23,Day
2,1/5/2026 15:58:26,1.16.3,Light Trk,0,3.69,NaN,1,Right,Left,1,1,1,0,NaN,NaN,0.03,2026-01-05 15:58:26,2026-01-05,15:58:26,Day
3,1/5/2026 15:58:41,1.16.3,Light Trk,0,3.69,NaN,1,Right,Left,1,2,1,0,NaN,NaN,0.07,2026-01-05 15:58:41,2026-01-05,15:58:41,Day
4,1/5/2026 17:18:26,1.16.3,Light Trk,0,3.82,NaN,1,Left,Left,2,2,1,0,NaN,NaN,0.17,2026-01-05 17:18:26,2026-01-05,17:18:26,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,1/7/2026 5:37:16,1.16.3,Light Trk,0,4.13,NaN,1,Right,Right,409,262,321,0,NaN,NaN,0.00,2026-01-07 05:37:16,2026-01-07,05:37:16,Night
992,1/7/2026 5:37:17,1.16.3,Light Trk,0,4.13,2.0,1,Pellet,Right,409,262,322,0,0.06,16.0,NaN,2026-01-07 05:37:17,2026-01-07,05:37:17,Night
993,1/7/2026 5:37:47,1.16.3,Light Trk,0,4.13,NaN,1,Left,Left,410,262,322,0,NaN,NaN,0.00,2026-01-07 05:37:47,2026-01-07,05:37:47,Night
994,1/7/2026 5:37:48,1.16.3,Light Trk,0,4.14,1.0,1,Pellet,Left,410,262,323,0,0.19,31.0,NaN,2026-01-07 05:37:48,2026-01-07,05:37:48,Night
995,1/7/2026 5:37:49,1.16.3,Light Trk,0,4.14,NaN,1,LeftinTimeOut,Left,411,262,323,0,NaN,NaN,NaN,2026-01-07 05:37:49,2026-01-07,05:37:49,Night

In [8]:
print(df.columns.tolist())

['MM:DD:YYYY hh:mm:ss', 'Library_Version', 'Session_type', 'Device_Number', 'Battery_Voltage', 'Motor_Turns', 'FR', 'Event', 'Active_Poke', 'Left_Poke_Count', 'Right_Poke_Count', 'Pellet_Count', 'Block_Pellet_Count', 'Retrieval_Time', 'InterPelletInterval', 'Poke_Time', 'Datetime', 'Date', 'Hour', 'Period']

In [9]:
df.to_csv(output_file, index=False)

# ✅ Confirmation + aperçu
print("\n✅ Le fichier a bien été enregistré !")
print(f"📍 Chemin : {output_file}")
print("\n🔍 Aperçu des premières lignes du fichier modifié :")
display(df.head())

✅ Le fichier a bien été enregistré !
📍 Chemin : \\10.69.168.1\crnldata\forgetting\Carla\Fed\APPPS1\AHAD01.38\12 mois\AHAD01.38_05_01_2026au07_01_2026_Periodic.csv

🔍 Aperçu des premières lignes du fichier modifié :

,MM:DD:YYYY hh:mm:ss,Library_Version,Session_type,Device_Number,Battery_Voltage,Motor_Turns,FR,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time,Datetime,Date,Hour,Period
0,1/5/2026 15:30:16,1.16.3,Light Trk,0,3.69,NaN,1,Left,Left,1,0,0,0,NaN,NaN,0.06,2026-01-05 15:30:16,2026-01-05,15:30:16,Day
1,1/5/2026 15:30:23,1.16.3,Light Trk,0,3.69,4.0,1,Pellet,Left,1,0,1,0,0.06,NaN,NaN,2026-01-05 15:30:23,2026-01-05,15:30:23,Day
2,1/5/2026 15:58:26,1.16.3,Light Trk,0,3.69,NaN,1,Right,Left,1,1,1,0,NaN,NaN,0.03,2026-01-05 15:58:26,2026-01-05,15:58:26,Day
3,1/5/2026 15:58:41,1.16.3,Light Trk,0,3.69,NaN,1,Right,Left,1,2,1,0,NaN,NaN,0.07,2026-01-05 15:58:41,2026-01-05,15:58:41,Day
4,1/5/2026 17:18:26,1.16.3,Light Trk,0,3.82,NaN,1,Left,Left,2,2,1,0,NaN,NaN,0.17,2026-01-05 17:18:26,2026-01-05,17:18:26,Day

In [10]:
# Afficher les événements uniques pour vérification
print("Types d'événements dans les données :")
print(df['Event'].unique())

# Assurer format cohérent
df['Datetime'] = pd.to_datetime(df['MM:DD:YYYY hh:mm:ss'], errors='coerce')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.date
df['Hour'] = pd.to_datetime(df['Hour'], format='%H:%M:%S', errors='coerce').dt.time

# Trier les données par date et heure
df = df.sort_values(['Date', 'Hour']).reset_index(drop=True)

# Créer un identifiant de bloc pour les périodes consécutives
# Cela va identifier chaque changement de période (Day->Night ou Night->Day)
df['Period_Block'] = (df['Period'] != df['Period'].shift(1)).cumsum()

# Définir les catégories d'événements
specific_events = [
    'LeftDuringDispense',
    'RightDuringDispense',
    'LeftWithPellet',
    'RightWithPellet',
    'RightinTimeOut',
    'LeftinTimeOut'
]

results = []

# Regrouper par bloc de période (périodes consécutives)
for (period_block), group in df.groupby('Period_Block'):
    # Le period_type est le même pour tout le groupe (Day ou Night)
    period_type = group['Period'].iloc[0]
    
    left_pokes = group[group['Event'] == 'Left'].shape[0]
    right_pokes = group[group['Event'] == 'Right'].shape[0]
    total_pokes = left_pokes + right_pokes
    correct = (group['Event'] == group['Active_Poke']).sum()
    
    # Comptage des pellets
    pellets = group[group['Event'] == 'Pellet'].shape[0]
    
    # First poke après Pellet
    pellet_indices = group[group['Event'] == 'Pellet'].index
    first_pokes = []
    for idx in pellet_indices:
        if idx + 1 in group.index:
            first_pokes.append(group.loc[idx + 1])
    first_pokes_df = pd.DataFrame(first_pokes)
    first_poke_total = len(first_pokes)
    first_poke_correct = (first_pokes_df['Event'] == first_pokes_df['Active_Poke']).sum() if not first_pokes_df.empty else 0
    
    # Calcul des pourcentages
    pct_first_poke_correct = round((first_poke_correct / first_poke_total) * 100, 2) if first_poke_total > 0 else None
    pct_correct = round((correct / total_pokes) * 100, 2) if total_pokes > 0 else None
    
    # Specific events
    spec_events = group[group['Event'].isin(specific_events)].shape[0]
    
    # Dates de début et fin du bloc
    start_date = group['Date'].min()
    end_date = group['Date'].max()
    
    results.append({
        'Period Block': period_block,
        'Period Type': period_type,
        'Start Date': start_date,
        'End Date': end_date,
        'Pellet': pellets,
        'Pokes': total_pokes,
        'Left Pokes': left_pokes,
        'Right Pokes': right_pokes,
        'Correct': correct,
        '% Correct': pct_correct,
        'First Poke': first_poke_total,
        'First Poke Correct': first_poke_correct,
        '% First Poke Correct': pct_first_poke_correct,
        'Specific Events': spec_events,
    })

# Résumé
summary_df = pd.DataFrame(results)
summary_df

Types d'événements dans les données :
['Left' 'Pellet' 'Right' 'RightDuringDispense' 'RightinTimeout'
 'LeftinTimeOut' 'LeftDuringDispense']

,Period Block,Period Type,Start Date,End Date,Pellet,Pokes,Left Pokes,Right Pokes,Correct,% Correct,First Poke,First Poke Correct,% First Poke Correct,Specific Events
0,1,Day,2026-01-05,2026-01-05,2,4,2,2,2,50.00,1,0,0.0,0
1,2,Night,2026-01-05,2026-01-07,321,525,305,220,321,61.14,321,217,67.6,108

In [11]:
# Sauvegarde CSV
base = os.path.splitext(os.path.basename(output_file))[0]
output_summary = os.path.join(folder, f"{base}_global.csv")
summary_df.to_csv(output_summary, index=False)

print(f"\n✅ Fichier résumé sauvegardé avec succès !")
print(f"📍 Chemin : {output_summary}")
display(summary_df)

✅ Fichier résumé sauvegardé avec succès !
📍 Chemin : \\10.69.168.1\crnldata\forgetting\Carla\Fed\APPPS1\AHAD01.38\12 mois\AHAD01.38_05_01_2026au07_01_2026_Periodic_global.csv

,Period Block,Period Type,Start Date,End Date,Pellet,Pokes,Left Pokes,Right Pokes,Correct,% Correct,First Poke,First Poke Correct,% First Poke Correct,Specific Events
0,1,Day,2026-01-05,2026-01-05,2,4,2,2,2,50.00,1,0,0.0,0
1,2,Night,2026-01-05,2026-01-07,321,525,305,220,321,61.14,321,217,67.6,108