In [1]:
import pandas as pd
from datetime import time
from ipyfilechooser import FileChooser
from IPython.display import display
import os


# 🎛️ Interface de sélection de fichier
fc_input = FileChooser("//10.69.168.1/crnldata/forgetting/Carla", select_default=True,show_only_dirs=False, title="<b>Sélectionnez le fichier CSV</b>")
display(fc_input)

# 📂 Fonction appelée après sélection du fichier
def update_input_file(chooser):
    global input_file_path
    input_file_path = chooser.selected
    print(f"\n📂 Fichier sélectionné : {input_file_path}")

FileChooser(path='\\10.69.168.1\crnldata\forgetting\Carla', filename='', title='<b>Sélectionnez le fichier CSV…

In [2]:
# Utiliser directement la propriété .selected du sélecteur
if fc_input.selected:
    input_file_path = fc_input.selected
    print(f"📂 Fichier sélectionné : {input_file_path}")
    
    df = pd.read_csv(input_file_path)
    df.columns = df.columns.str.replace(r'\+AF8-', '_', regex=True)
    print(f"✅ Fichier chargé : {len(df)} lignes, {len(df.columns)} colonnes")
    display(df)
else:
    print("❌ Veuillez d'abord sélectionner un fichier dans l'interface ci-dessus")

📂 Fichier sélectionné : \\10.69.168.1\crnldata\forgetting\Carla\Fed\WT\AHAD11.74\4 mois\AHAD11.74_08_10_2025au10_10_2025.CSV
✅ Fichier chargé : 1346 lignes, 1 colonnes

     MM:DD:YYYY hh:mm:ss;Session_type;Device_Number;Battery_Voltage;Motor_Turns;FR;Event;Active_Poke;Left_Poke_Count;Right_Poke_Count;Pellet_Count;Block_Pellet_Count;Retrieval_Time;InterPelletInterval;Poke_Time
0     10/08/2025 17:48;Light Trk;0;4.2;;1;Left;Left;...
1     10/08/2025 17:48;Light Trk;0;4.2;;1;LeftDuring...
2     10/08/2025 17:53;Light Trk;0;4.2;2.0;1;Pellet;...
3     10/08/2025 17:53;Light Trk;0;4.2;;1;Left;Left;...
4     10/08/2025 17:53;Light Trk;0;4.2;;1;LeftDuring...
...                                                 ...
1341  10/10/2025 08:52;Light Trk;0;3.93;2.0;1;Pellet...
1342  10/10/2025 08:52;Light Trk;0;3.93;;1;Right;Rig...
1343  10/10/2025 08:52;Light Trk;0;3.93;2.0;1;Pellet...
1344  10/10/2025 08:52;Light Trk;0;3.93;;1;Right;Lef...
1345  10/10/2025 08:52;Light Trk;0;3.93;;1;Right;Lef...

[1346 rows x 1 columns]

In [14]:
# 📌 Colonnes à supprimer
cols_to_drop = [
    'Library_Version', 'Session_type', 'Device_Number',
    'Battery_Voltage', 'Motor_Turns', 'FR'
]   
# 🧹 Supprimer les colonnes indésirables
df.drop(columns=[col for col in cols_to_drop if col in df.columns], inplace=True)
df

,MM:DD:YYYY hh:mm:ss,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time,Datetime,Date,Hour,Period,Period_Block
0,10/08/2025 17:48,Left,Left,1,0,0,0,NaN,NaN,0.00,2025-10-08 17:48:00,2025-10-08,17:48:00,Day,1
1,10/08/2025 17:48,LeftDuringDispense,Left,2,0,0,0,NaN,NaN,0.00,2025-10-08 17:48:00,2025-10-08,17:48:00,Day,1
2,10/08/2025 17:53,Pellet,Left,2,0,1,0,Timed_out,NaN,NaN,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
3,10/08/2025 17:53,Left,Left,3,0,1,0,NaN,NaN,0.00,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
4,10/08/2025 17:53,LeftDuringDispense,Left,4,0,1,0,NaN,NaN,0.19,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10/10/2025 08:52,Pellet,Left,520,578,244,0,0.25,41.0,NaN,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1342,10/10/2025 08:52,Right,Right,520,579,244,0,NaN,NaN,0.00,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1343,10/10/2025 08:52,Pellet,Right,520,579,245,0,0.06,23.0,NaN,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1344,10/10/2025 08:52,Right,Left,520,580,245,0,NaN,NaN,0.16,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1345,10/10/2025 08:52,Right,Left,520,581,245,0,NaN,NaN,0.33,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5

In [15]:
#df = pd.read_csv(input_file_path, sep=';')

In [16]:

# 🕒 Convertir la colonne datetime
df['Datetime'] = pd.to_datetime(df['MM:DD:YYYY hh:mm:ss'], errors='coerce')
print(df['Datetime'].astype(str))  # Force l'affichage complet

# 🗓️ Extraire Date et Hour
df['Date'] = df['Datetime'].dt.date
df['Hour'] = df['Datetime'].dt.time

#df.rename(columns={'Active_Poke': 'ActivePoke'}, inplace=True)

# ☀️ Déterminer la période Day/Night
def get_period(hour):
    if pd.isnull(hour):
        return None
    if time(7, 0, 1) <= hour <= time(19, 0, 0):
        return "Day"
    else:
        return "Night"

df['Period'] = df['Hour'].apply(get_period)

# 💾 Enregistrer dans le même dossier avec _modifié
folder = os.path.dirname(input_file_path)
base = os.path.splitext(os.path.basename(input_file_path))[0]
output_file = os.path.join(folder, f"{base}_Periodic.csv")

df

0       2025-10-08 17:48:00
1       2025-10-08 17:48:00
2       2025-10-08 17:53:00
3       2025-10-08 17:53:00
4       2025-10-08 17:53:00
               ...
1341    2025-10-10 08:52:00
1342    2025-10-10 08:52:00
1343    2025-10-10 08:52:00
1344    2025-10-10 08:52:00
1345    2025-10-10 08:52:00
Name: Datetime, Length: 1346, dtype: object

,MM:DD:YYYY hh:mm:ss,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time,Datetime,Date,Hour,Period,Period_Block
0,10/08/2025 17:48,Left,Left,1,0,0,0,NaN,NaN,0.00,2025-10-08 17:48:00,2025-10-08,17:48:00,Day,1
1,10/08/2025 17:48,LeftDuringDispense,Left,2,0,0,0,NaN,NaN,0.00,2025-10-08 17:48:00,2025-10-08,17:48:00,Day,1
2,10/08/2025 17:53,Pellet,Left,2,0,1,0,Timed_out,NaN,NaN,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
3,10/08/2025 17:53,Left,Left,3,0,1,0,NaN,NaN,0.00,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
4,10/08/2025 17:53,LeftDuringDispense,Left,4,0,1,0,NaN,NaN,0.19,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10/10/2025 08:52,Pellet,Left,520,578,244,0,0.25,41.0,NaN,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1342,10/10/2025 08:52,Right,Right,520,579,244,0,NaN,NaN,0.00,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1343,10/10/2025 08:52,Pellet,Right,520,579,245,0,0.06,23.0,NaN,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1344,10/10/2025 08:52,Right,Left,520,580,245,0,NaN,NaN,0.16,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5
1345,10/10/2025 08:52,Right,Left,520,581,245,0,NaN,NaN,0.33,2025-10-10 08:52:00,2025-10-10,08:52:00,Day,5

In [17]:
df.to_csv(output_file, index=False)

# ✅ Confirmation + aperçu
print("\n✅ Le fichier a bien été enregistré !")
print(f"📍 Chemin : {output_file}")
print("\n🔍 Aperçu des premières lignes du fichier modifié :")
display(df.head())

✅ Le fichier a bien été enregistré !
📍 Chemin : \\10.69.168.1\crnldata\forgetting\Carla\Fed\WT\AHAD11.74\4 mois\AHAD11.74_08_10_2025au10_10_2025_Periodic.csv

🔍 Aperçu des premières lignes du fichier modifié :

,MM:DD:YYYY hh:mm:ss,Event,Active_Poke,Left_Poke_Count,Right_Poke_Count,Pellet_Count,Block_Pellet_Count,Retrieval_Time,InterPelletInterval,Poke_Time,Datetime,Date,Hour,Period,Period_Block
0,10/08/2025 17:48,Left,Left,1,0,0,0,NaN,NaN,0.00,2025-10-08 17:48:00,2025-10-08,17:48:00,Day,1
1,10/08/2025 17:48,LeftDuringDispense,Left,2,0,0,0,NaN,NaN,0.00,2025-10-08 17:48:00,2025-10-08,17:48:00,Day,1
2,10/08/2025 17:53,Pellet,Left,2,0,1,0,Timed_out,NaN,NaN,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
3,10/08/2025 17:53,Left,Left,3,0,1,0,NaN,NaN,0.00,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1
4,10/08/2025 17:53,LeftDuringDispense,Left,4,0,1,0,NaN,NaN,0.19,2025-10-08 17:53:00,2025-10-08,17:53:00,Day,1

In [18]:
# Afficher les événements uniques pour vérification
print("Types d'événements dans les données :")
print(df['Event'].unique())

# Assurer format cohérent
df['Datetime'] = pd.to_datetime(df['MM:DD:YYYY hh:mm:ss'], errors='coerce')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.date
df['Hour'] = pd.to_datetime(df['Hour'], format='%H:%M:%S', errors='coerce').dt.time

# Trier les données par date et heure
df = df.sort_values(['Date', 'Hour']).reset_index(drop=True)

# Créer un identifiant de bloc pour les périodes consécutives
# Cela va identifier chaque changement de période (Day->Night ou Night->Day)
df['Period_Block'] = (df['Period'] != df['Period'].shift(1)).cumsum()

# Définir les catégories d'événements
specific_events = [
    'LeftDuringDispense',
    'RightDuringDispense',
    'LeftWithPellet',
    'RightWithPellet',
    'RightinTimeOut',
    'LeftinTimeOut'
]

results = []

# Regrouper par bloc de période (périodes consécutives)
for (period_block), group in df.groupby('Period_Block'):
    # Le period_type est le même pour tout le groupe (Day ou Night)
    period_type = group['Period'].iloc[0]
    
    left_pokes = group[group['Event'] == 'Left'].shape[0]
    right_pokes = group[group['Event'] == 'Right'].shape[0]
    total_pokes = left_pokes + right_pokes
    correct = (group['Event'] == group['Active_Poke']).sum()
    
    # Comptage des pellets
    pellets = group[group['Event'] == 'Pellet'].shape[0]
    
    # First poke après Pellet
    pellet_indices = group[group['Event'] == 'Pellet'].index
    first_pokes = []
    for idx in pellet_indices:
        if idx + 1 in group.index:
            first_pokes.append(group.loc[idx + 1])
    first_pokes_df = pd.DataFrame(first_pokes)
    first_poke_total = len(first_pokes)
    first_poke_correct = (first_pokes_df['Event'] == first_pokes_df['Active_Poke']).sum() if not first_pokes_df.empty else 0
    
    # Calcul des pourcentages
    pct_first_poke_correct = round((first_poke_correct / first_poke_total) * 100, 2) if first_poke_total > 0 else None
    pct_correct = round((correct / total_pokes) * 100, 2) if total_pokes > 0 else None
    
    # Specific events
    spec_events = group[group['Event'].isin(specific_events)].shape[0]
    
    # Dates de début et fin du bloc
    start_date = group['Date'].min()
    end_date = group['Date'].max()
    
    results.append({
        'Period Block': period_block,
        'Period Type': period_type,
        'Start Date': start_date,
        'End Date': end_date,
        'Pellet': pellets,
        'Pokes': total_pokes,
        'Left Pokes': left_pokes,
        'Right Pokes': right_pokes,
        'Correct': correct,
        '% Correct': pct_correct,
        'First Poke': first_poke_total,
        'First Poke Correct': first_poke_correct,
        '% First Poke Correct': pct_first_poke_correct,
        'Specific Events': spec_events,
    })

# Résumé
summary_df = pd.DataFrame(results)
summary_df

Types d'événements dans les données :
['Left' 'LeftDuringDispense' 'Pellet' 'Right' 'RightWithPellet'
 'LeftWithPellet' 'RightinTimeout' 'LeftinTimeOut' 'RightDuringDispense']

,Period Block,Period Type,Start Date,End Date,Pellet,Pokes,Left Pokes,Right Pokes,Correct,% Correct,First Poke,First Poke Correct,% First Poke Correct,Specific Events
0,1,Day,2025-10-08,2025-10-08,6,13,10,3,6,46.15,6,3,50.00,3
1,2,Night,2025-10-08,2025-10-09,69,100,47,53,69,69.00,68,6,8.82,564
2,3,Day,2025-10-09,2025-10-09,78,128,75,53,78,60.94,77,47,61.04,25
3,4,Night,2025-10-09,2025-10-10,86,148,52,96,86,58.11,85,69,81.18,5
4,5,Day,2025-10-10,2025-10-10,6,10,5,5,6,60.00,6,4,66.67,0

In [19]:
# Sauvegarde CSV
base = os.path.splitext(os.path.basename(output_file))[0]
output_summary = os.path.join(folder, f"{base}_global.csv")
summary_df.to_csv(output_summary, index=False)

print(f"\n✅ Fichier résumé sauvegardé avec succès !")
print(f"📍 Chemin : {output_summary}")
display(summary_df)

✅ Fichier résumé sauvegardé avec succès !
📍 Chemin : \\10.69.168.1\crnldata\forgetting\Carla\Fed\WT\AHAD11.74\4 mois\AHAD11.74_08_10_2025au10_10_2025_Periodic_global.csv

,Period Block,Period Type,Start Date,End Date,Pellet,Pokes,Left Pokes,Right Pokes,Correct,% Correct,First Poke,First Poke Correct,% First Poke Correct,Specific Events
0,1,Day,2025-10-08,2025-10-08,6,13,10,3,6,46.15,6,3,50.00,3
1,2,Night,2025-10-08,2025-10-09,69,100,47,53,69,69.00,68,6,8.82,564
2,3,Day,2025-10-09,2025-10-09,78,128,75,53,78,60.94,77,47,61.04,25
3,4,Night,2025-10-09,2025-10-10,86,148,52,96,86,58.11,85,69,81.18,5
4,5,Day,2025-10-10,2025-10-10,6,10,5,5,6,60.00,6,4,66.67,0